# Generated by Django 2.1.2 on 2018-11-04 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('perfil', models.CharField(default='Invitado', max_length=20)),
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('region', models.CharField(default='Metropolitana', max_length=20)),
                ('ciudad', models.CharField(default='Santiago', max_length=20)),
                ('tipoHogar', models.CharField(default='Departamento', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
