# Generated by Django 2.1.2 on 2018-11-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='region',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipoHogar',
        ),
    ]
