# Generated by Django 2.1.2 on 2018-11-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_auto_20181104_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('fichaMascota', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombreMascota', models.CharField(max_length=50)),
                ('razaMascota', models.CharField(max_length=50)),
            ],
        ),
    ]
